[package]
name = "branches"
version = "0.1.0"
authors = ["Zhen Yi Lim <zhen.yi@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"